travis:
  secure:
    BINSTAR_TOKEN: ZpNVJ4RinJpdLYKuOYBjsFO+LXCfx0hmLX7EKqWnQpiaxJmokA91m5HQu3BhEDnXO6fMoHCvFWo6PcP9ha1l7WoV7Glmv0WTNFuHadcDYZgB/kwNSCSuF0y50x/xHHUMXnzwU73Zyknb+gaZaRVpNrXN8rIO9bh28YRWsvSHP5bauRzV7wOeVtZfMpWeyGyGw4tgXWZKUuzq6jK//rJxAd6dEWfZ/nlVFo+Ba5FsD1MFy6qFSFtYFSA9DkJTlQITGPJViFGckkSPa3Pw3eBjHdIve4IQ1P1rS/P2HUeSb2bs3SV3OAHgIQNbcVE0QRIlbxAZzROqdKZ7AIzm1mRH1kFPhab2y5IMmUUJdlu1Dnjy3W13EE9LTxafAdwoCK7r91Sl8h9HcJGnaAp1nN4K+SeRgXNWUEaFSuXbiFkA8hQ8abk6l+hVa7SijNbAu9uZamYv6JM7AX52JPh/CPSGUK7cH7m1aOG5CdAwOBWfrjFcjp8tAuzriTiJUobuYvHWk1nRB7NIsYEAXoVIbj7O1Kudg/UBl93sAAzvOaIPmNG/DVRwoxCU8vAxG8an/YRjRJHpLZM7py41N4nBIvUBfmW3zITZNrMx4r+0TR8Mc1UamzN+ivHtrFJvpFivQ0vSEpkevTpXbQeCaa2fv3HMbu4KXAYeMXphWBTUCwcmR7A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
